# Generated by Django 5.1.1 on 2024-10-07 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."category',
                "indexes": [
                    models.Index(fields=["name"], name="category_name_d601b7_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Finish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."finish',
                "indexes": [
                    models.Index(fields=["name"], name="finish_name_daa627_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."material',
                "indexes": [
                    models.Index(fields=["name"], name="material_name_88ae6c_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("contact_email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("csv_mapping", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."seller',
                "indexes": [
                    models.Index(fields=["name"], name="seller_name_0007ce_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ThreadSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "thread_type",
                    models.CharField(
                        choices=[("metric", "metric"), ("imperial", "imperial")],
                        max_length=50,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("millimeter", "millimeter"), ("inch", "inch")],
                        max_length=50,
                    ),
                ),
                (
                    "metric_size_str",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("metric_size_num", models.FloatField(blank=True, null=True)),
                (
                    "imperial_size_str",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("imperial_size_num", models.FloatField(blank=True, null=True)),
                ("thread_per_unit", models.FloatField()),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."thread_size',
                "indexes": [
                    models.Index(fields=["name"], name="thread_size_name_d8604e_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Fastener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasteners",
                        to="fastener_app.category",
                    ),
                ),
                (
                    "finish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasteners",
                        to="fastener_app.finish",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasteners",
                        to="fastener_app.material",
                    ),
                ),
                (
                    "thread_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasteners",
                        to="fastener_app.threadsize",
                    ),
                ),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."fastener',
            },
        ),
        migrations.CreateModel(
            name="SellerFastener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "fastener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_fasteners",
                        to="fastener_app.fastener",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_fasteners",
                        to="fastener_app.seller",
                    ),
                ),
            ],
            options={
                "db_table": f'{settings.DB_SCHEMA}"."seller_fastener',
                "unique_together": {("seller", "fastener")},
            },
        ),
        migrations.AddIndex(
            model_name="fastener",
            index=models.Index(fields=["description"], name="fastener_name"),
        ),
        migrations.AddIndex(
            model_name="fastener",
            index=models.Index(
                fields=["thread_size", "material", "finish", "category"],
                name="features",
            ),
        ),
    ]
